"""creacion marca

Revision ID: 390519a14500
Revises: 
Create Date: 2024-06-18 21:05:01.302719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390519a14500'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marca')
    # ### end Alembic commands ###
